# Generated by Django 3.1.2 on 2020-10-05 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberCSVFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='uploads/csv/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('client_member_id', models.IntegerField()),
                ('memberlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='members',
            field=models.ManyToManyField(related_name='lists', to='Members.Member'),
        ),
    ]
